[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600
command_blacklist =
connection_timeout = 200

[tidal]
enabled = true
quality = HI_RES_LOSSLESS
auth_method = OAUTH
login_method = BLOCK
lazy = true

[audio]
output = pulsesink
